### PR TITLE
RAI Russian Whitepaper

### PR DESCRIPTION
**Pull request by NeoSPU**
Hi! I'm a worker from GitCoin task (https://gitcoin.co/issue/reflexer-labs/whitepapers/2/100024987)
I've been done translate the RAI Whitepaper from English to Russian
How I can get RAI address for submission ma work to pay?

Get please my rai-russian.pdf file with my Pull Request.
Thx.

### CODE REVIEW

**Comment by stefanionescu** [comment]
> Hi! I'm a worker from GitCoin task (https://gitcoin.co/issue/reflexer-labs/whitepapers/2/100024987)
> I've been done translate the RAI Whitepaper from English to Russian
> How I can get RAI address for submission ma work to pay?
> 
> Get please my rai-russian.pdf file with my Pull Request.
> Thx.

Thanks for this. You should go to Gitcoin and appply to the bounty. We will evaluate submissions in a couple of weeks from now.

https://gitcoin.co/issue/reflexer-labs/whitepapers/2/100024987

**Comment by NeoSPU** [comment]
Ok! I've done it and wrote my ETH address! Good luck!

**Comment by NeoSPU** [comment]
Hi! I've been finished my work by translate RAI white paper to Russian (https://gitcoin.co/issue/reflexer-labs/whitepapers/2/100024987) 19 days ago! I'd like to get my bounty this up soon! Regards to you!
My ETH wallet is 0xe086A89CF0ca433d7bCaeBf9d82735217A3aa090

**Comment by stefanionescu** [comment]
@NeoSPU you got the bounty, congrats!

**Pull request closed without merging**
